package CA2;

import javax.swing.*;
import java.awt.*;

public class StudentLibrarySystem extends javax.swing.JFrame {

    /**
     * Creates new form StudentAndBookManagementFrame
     */
    public StudentLibrarySystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSearchBySelected = new javax.swing.ButtonGroup();
        lblPageTitle = new javax.swing.JLabel();
        pnlStudentInfo = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtStudentID = new javax.swing.JTextField();
        btnStudentPrevious = new javax.swing.JButton();
        btnStudentNext = new javax.swing.JButton();
        btnStudentFirst = new javax.swing.JButton();
        btnStudentLast = new javax.swing.JButton();
        pnlBookInfo = new javax.swing.JPanel();
        lblBookTitle = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        lblBookAuthor = new javax.swing.JLabel();
        txtBookAuthor = new javax.swing.JTextField();
        lblBookISBN = new javax.swing.JLabel();
        txtBookISBN = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        lblAvailable = new javax.swing.JLabel();
        txtAvailable = new javax.swing.JTextField();
        btnBookPrevious = new javax.swing.JButton();
        btnBookNext = new javax.swing.JButton();
        btnBookFirst = new javax.swing.JButton();
        btnBookLast = new javax.swing.JButton();
        pnlSearchSelected = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        radioBtnSearchByStudent = new javax.swing.JRadioButton();
        radioBtnSearchByBook = new javax.swing.JRadioButton();
        txtSearchBySelected = new javax.swing.JTextField();
        btnSearchBySelected = new javax.swing.JButton();
        lblFolderIcon = new javax.swing.JLabel();
        lblSearchResults = new javax.swing.JLabel();
        scrPaneSearchResults = new javax.swing.JScrollPane();
        txtAreaSearchResults = new javax.swing.JTextArea();
        btnDisplayStudentInformation = new javax.swing.JButton();
        btnDisplayBookInformation = new javax.swing.JButton();
        btnExitProgram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student and Book Management");

        lblPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(2, 48, 255));
        lblPageTitle.setText("Student and Book Management");

        pnlStudentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student 1 of 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        lblStudentName.setText("👤 Name:");

        lblStudentID.setText("🆔 Student ID:");

        txtStudentName.setEditable(false);
        txtStudentName.setFocusable(false);

        txtStudentID.setEditable(false);

        btnStudentPrevious.setText("Previous");

        btnStudentNext.setText("Next");

        btnStudentFirst.setText("First");

        btnStudentLast.setText("Last");

        javax.swing.GroupLayout pnlStudentInfoLayout = new javax.swing.GroupLayout(pnlStudentInfo);
        pnlStudentInfo.setLayout(pnlStudentInfoLayout);
        pnlStudentInfoLayout.setHorizontalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                        .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStudentName)
                            .addComponent(txtStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                        .addComponent(btnStudentPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStudentNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStudentFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStudentLast)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStudentInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnStudentFirst, btnStudentLast, btnStudentNext, btnStudentPrevious});

        pnlStudentInfoLayout.setVerticalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentPrevious)
                    .addComponent(btnStudentNext)
                    .addComponent(btnStudentFirst)
                    .addComponent(btnStudentLast))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStudentInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnStudentFirst, btnStudentLast, btnStudentNext, btnStudentPrevious});

        pnlBookInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book 1 of 5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        lblBookTitle.setText("📘 Title:");

        txtBookTitle.setEditable(false);
        txtBookTitle.setFocusable(false);

        lblBookAuthor.setText("👤 Author:");

        txtBookAuthor.setEditable(false);

        lblBookISBN.setText("📃 ISBN:");

        txtBookISBN.setEditable(false);
        txtBookISBN.setFocusable(false);

        lblPrice.setText("💲 Price:");

        txtPrice.setEditable(false);

        lblCategory.setText("📚 Category:");

        txtCategory.setEditable(false);
        txtCategory.setFocusable(false);

        lblAvailable.setText("✔️ Available:");

        txtAvailable.setEditable(false);

        btnBookPrevious.setText("Previous");

        btnBookNext.setText("Next");

        btnBookFirst.setText("First");

        btnBookLast.setText("Last");

        javax.swing.GroupLayout pnlBookInfoLayout = new javax.swing.GroupLayout(pnlBookInfo);
        pnlBookInfo.setLayout(pnlBookInfoLayout);
        pnlBookInfoLayout.setHorizontalGroup(
            pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBookISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBookISBN)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBookAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBookTitle)
                            .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCategory)
                            .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addComponent(btnBookPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBookNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBookFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBookLast)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pnlBookInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBookFirst, btnBookLast, btnBookNext, btnBookPrevious});

        pnlBookInfoLayout.setVerticalGroup(
            pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookTitle)
                    .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookAuthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookISBN)
                    .addComponent(txtBookISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailable))
                .addGap(18, 18, 18)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookPrevious)
                    .addComponent(btnBookNext)
                    .addComponent(btnBookFirst)
                    .addComponent(btnBookLast))
                .addContainerGap())
        );

        pnlBookInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBookFirst, btnBookLast, btnBookNext, btnBookPrevious});

        pnlSearchSelected.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblSearch.setText("🔎 Search:");

        btnGrpSearchBySelected.add(radioBtnSearchByStudent);
        radioBtnSearchByStudent.setText("👤 by Student");

        btnGrpSearchBySelected.add(radioBtnSearchByBook);
        radioBtnSearchByBook.setText("📕 by Book");
        radioBtnSearchByBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnSearchByBookActionPerformed(evt);
            }
        });

        btnSearchBySelected.setText("🔎 Search");

        javax.swing.GroupLayout pnlSearchSelectedLayout = new javax.swing.GroupLayout(pnlSearchSelected);
        pnlSearchSelected.setLayout(pnlSearchSelectedLayout);
        pnlSearchSelectedLayout.setHorizontalGroup(
            pnlSearchSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchSelectedLayout.createSequentialGroup()
                .addGroup(pnlSearchSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchSelectedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSearch))
                    .addGroup(pnlSearchSelectedLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlSearchSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchBySelected, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlSearchSelectedLayout.createSequentialGroup()
                                .addComponent(radioBtnSearchByStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnSearchByBook, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearchBySelected))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchSelectedLayout.setVerticalGroup(
            pnlSearchSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchSelectedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSearchSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnSearchByStudent)
                    .addComponent(radioBtnSearchByBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchBySelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchBySelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFolderIcon.setText("📂");

        lblSearchResults.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSearchResults.setText("Search Results: ");

        txtAreaSearchResults.setColumns(20);
        txtAreaSearchResults.setRows(5);
        scrPaneSearchResults.setViewportView(txtAreaSearchResults);

        btnDisplayStudentInformation.setText("👤 Display Student Information");

        btnDisplayBookInformation.setText("📕 Display Book Information");

        btnExitProgram.setText("🔚 Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlBookInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudentInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSearchSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrPaneSearchResults)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFolderIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSearchResults))
                            .addComponent(btnDisplayStudentInformation)
                            .addComponent(btnDisplayBookInformation)
                            .addComponent(btnExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lblPageTitle)
                .addGap(255, 255, 255))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDisplayBookInformation, btnDisplayStudentInformation});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSearchSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFolderIcon)
                            .addComponent(lblSearchResults))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPaneSearchResults, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisplayStudentInformation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisplayBookInformation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExitProgram)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnSearchByBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnSearchByBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnSearchByBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLibrarySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLibrarySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLibrarySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLibrarySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                var mainFrame = new StudentLibrarySystem();
                mainFrame.setLocationRelativeTo(null);
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookFirst;
    private javax.swing.JButton btnBookLast;
    private javax.swing.JButton btnBookNext;
    private javax.swing.JButton btnBookPrevious;
    private javax.swing.JButton btnDisplayBookInformation;
    private javax.swing.JButton btnDisplayStudentInformation;
    private javax.swing.JButton btnExitProgram;
    private javax.swing.ButtonGroup btnGrpSearchBySelected;
    private javax.swing.JButton btnSearchBySelected;
    private javax.swing.JButton btnStudentFirst;
    private javax.swing.JButton btnStudentLast;
    private javax.swing.JButton btnStudentNext;
    private javax.swing.JButton btnStudentPrevious;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblBookAuthor;
    private javax.swing.JLabel lblBookISBN;
    private javax.swing.JLabel lblBookTitle;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblFolderIcon;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchResults;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JPanel pnlBookInfo;
    private javax.swing.JPanel pnlSearchSelected;
    private javax.swing.JPanel pnlStudentInfo;
    private javax.swing.JRadioButton radioBtnSearchByBook;
    private javax.swing.JRadioButton radioBtnSearchByStudent;
    private javax.swing.JScrollPane scrPaneSearchResults;
    private javax.swing.JTextArea txtAreaSearchResults;
    private javax.swing.JTextField txtAvailable;
    private javax.swing.JTextField txtBookAuthor;
    private javax.swing.JTextField txtBookISBN;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearchBySelected;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
